// Alpha Bookshelf — Kids Reading List
// Source: alpha-bookshelf-app.vercel.app (Storytime + Quest + Teen shells)
// Generated from public catalog metadata + editorial jacket copy.

export type Shell = "storytime" | "quest" | "teen";

export type LibraryBook = {
  id: string;
  title: string;
  shortTitle: string;
  author: string;
  year: string;
  description: string;
  cover: string;      // spine/jacket color (hex)
  accent: string;     // foil/accent color (hex)
  ink: string;        // primary type color (hex)
  grade: string | null;
  lexile: number | null;
  shells: Shell[];
  badges: string[];
  coverImage: string | null; // path under /public
  url: string;         // deep link to the Alpha Bookshelf detail page
};

export const alphaBookshelfKids: LibraryBook[] = [
  {
    id: "cat-kid-comic-club-on-purpose",
    title: "Cat Kid Comic Club: On Purpose",
    shortTitle: "Cat Kid Comic Club: On Purpose",
    author: "Dav Pilkey",
    year: "2023",
    description: "Cat Kid and the twenty-one baby frogs are back with a new round of homemade comics about art, feelings, and doing hard things on purpose.",
    cover: "#3fa66f",
    accent: "#f5c94a",
    ink: "#f4ead8",
    grade: null,
    lexile: null,
    shells: ["storytime"] as Shell[],
    badges: ["bestseller", "expert loved", "graphic novel"],
    coverImage: null,
    url: "https://alpha-bookshelf-app.vercel.app/book/cat-kid-comic-club-on-purpose",
  },
  {
    id: "chickenpox",
    title: "Chickenpox",
    shortTitle: "Chickenpox",
    author: "Remy Lai",
    year: "2024",
    description: "Abby is the oldest of five kids in a tiny apartment—and now everyone has chickenpox. A funny, itchy graphic novel about being big, small, and stuck at home.",
    cover: "#e8b7b0",
    accent: "#a53a3a",
    ink: "#4a1414",
    grade: null,
    lexile: null,
    shells: ["quest", "storytime"] as Shell[],
    badges: ["graphic novel", "kid favorite", "kid voted award"],
    coverImage: "/covers/chickenpox.jpg",
    url: "https://alpha-bookshelf-app.vercel.app/book/chickenpox",
  },
  {
    id: "cranky-crabby-crow-saves-the-world",
    title: "Cranky, Crabby Crow (Saves the World)",
    shortTitle: "Cranky, Crabby Crow (Saves the World)",
    author: "Corey R. Tabor",
    year: "2024",
    description: "One very cranky crow finds a very small friend, and together they save the world in the smallest, funniest way possible.",
    cover: "#1e2733",
    accent: "#f2a83c",
    ink: "#f3ecdc",
    grade: null,
    lexile: null,
    shells: ["storytime"] as Shell[],
    badges: ["expert loved", "kid favorite"],
    coverImage: null,
    url: "https://alpha-bookshelf-app.vercel.app/book/cranky-crabby-crow-saves-the-world",
  },
  {
    id: "dog-man",
    title: "Dog Man: Big Jim Believes: A Graphic Novel (Dog Man #14)",
    shortTitle: "Dog Man: Big Jim Believes: A Graphic Novel (Dog Man #14)",
    author: "Dav Pilkey",
    year: "2025",
    description: "Dog Man and Petey team up with an old friend to face a super-big new problem in this fourteenth graphic novel adventure.",
    cover: "#3555e0",
    accent: "#f5c94a",
    ink: "#f4ead8",
    grade: null,
    lexile: null,
    shells: ["quest", "storytime"] as Shell[],
    badges: ["bestseller", "graphic novel", "kid favorite"],
    coverImage: null,
    url: "https://alpha-bookshelf-app.vercel.app/book/dog-man",
  },
  {
    id: "junie-b-jones-and-the-stupid-smelly-bus-2",
    title: "Junie B. Jones and the Stupid Smelly Bus: The Graphic Novel",
    shortTitle: "Junie B. Jones and the Stupid Smelly Bus: The Graphic Novel",
    author: "Barbara Park, adapted by Colleen A.F. Venable",
    year: "2024",
    description: "Kindergartener Junie B. Jones decides she is not, no way, going home on the stupid smelly bus—so she hides at school. A graphic-novel remake of the classic first book.",
    cover: "#e6c94a",
    accent: "#c94a4a",
    ink: "#1e1a12",
    grade: null,
    lexile: null,
    shells: ["quest", "storytime"] as Shell[],
    badges: ["bestseller", "graphic novel", "kid voted award"],
    coverImage: null,
    url: "https://alpha-bookshelf-app.vercel.app/book/junie-b-jones-and-the-stupid-smelly-bus-2",
  },
  {
    id: "knight-owl",
    title: "Knight Owl",
    shortTitle: "Knight Owl",
    author: "Christopher Denise",
    year: "2022",
    description: "A very small owl gets a very big job protecting a castle at night, and discovers that being clever counts more than being fierce.",
    cover: "#2f2547",
    accent: "#e8c48a",
    ink: "#f4ead8",
    grade: null,
    lexile: null,
    shells: ["storytime"] as Shell[],
    badges: ["expert loved", "kid voted award", "read aloud favorite"],
    coverImage: "/covers/knight-owl.jpg",
    url: "https://alpha-bookshelf-app.vercel.app/book/knight-owl",
  },
  {
    id: "no-more-gnomes",
    title: "No More Gnomes",
    shortTitle: "No More Gnomes",
    author: "Beth Mills",
    year: "2024",
    description: "The gnomes are back, and this time they refuse to leave. A very small, very stubborn book about very small, very stubborn creatures.",
    cover: "#4a6a4a",
    accent: "#c94a4a",
    ink: "#f4ead8",
    grade: null,
    lexile: null,
    shells: ["storytime"] as Shell[],
    badges: ["bestseller", "booktok", "kid favorite"],
    coverImage: null,
    url: "https://alpha-bookshelf-app.vercel.app/book/no-more-gnomes",
  },
  {
    id: "the-book-of-turtles",
    title: "The Book of Turtles",
    shortTitle: "The Book of Turtles",
    author: "Sy Montgomery",
    year: "2023",
    description: "A gentle nonfiction love letter to the turtles that have quietly outlasted almost everything else on Earth.",
    cover: "#5a7d5a",
    accent: "#c99a5a",
    ink: "#f4ead8",
    grade: null,
    lexile: null,
    shells: ["storytime"] as Shell[],
    badges: ["bestseller", "expert loved"],
    coverImage: null,
    url: "https://alpha-bookshelf-app.vercel.app/book/the-book-of-turtles",
  },
  {
    id: "because-of-winndixie",
    title: "Because of Winn-Dixie",
    shortTitle: "Because of Winn-Dixie",
    author: "Kate DiCamillo",
    year: "2000",
    description: "India Opal Buloni is ten and new in town when a stray dog knocks over the produce display at the Winn-Dixie. She calls him Winn-Dixie, and he leads her to almost every friend she is about to make.",
    cover: "#a54d2a",
    accent: "#e8c48a",
    ink: "#f5eadb",
    grade: null,
    lexile: null,
    shells: ["quest"] as Shell[],
    badges: ["bestseller", "kid voted award", "read aloud favorite"],
    coverImage: null,
    url: "https://alpha-bookshelf-app.vercel.app/book/because-of-winndixie",
  },
  {
    id: "butt-or-face",
    title: "Butt or Face?: A Hilarious Animal Guessing Game",
    shortTitle: "Butt or Face?: A Hilarious Animal Guessing Game",
    author: "Kari Lavelle",
    year: "2023",
    description: "Twenty-two close-up animal photographs and one wildly funny question: is this a butt or a face? Kids peek, guess, and turn the page to find out.",
    cover: "#e6a53a",
    accent: "#3d2b8c",
    ink: "#1e1a12",
    grade: null,
    lexile: null,
    shells: ["quest"] as Shell[],
    badges: ["expert loved", "humor", "kid voted award"],
    coverImage: null,
    url: "https://alpha-bookshelf-app.vercel.app/book/butt-or-face",
  },
  {
    id: "diary-of-a-wimpy-kid",
    title: "Diary of a Wimpy Kid: Hot Mess",
    shortTitle: "Diary of a Wimpy Kid: Hot Mess",
    author: "Jeff Kinney",
    year: "2024",
    description: "Greg Heffley is trying to hold it together during the hottest summer of his life, and everything keeps melting down anyway.",
    cover: "#e8b23a",
    accent: "#1e1a12",
    ink: "#1e1a12",
    grade: null,
    lexile: null,
    shells: ["quest"] as Shell[],
    badges: ["bestseller", "kid favorite", "kid voted award"],
    coverImage: null,
    url: "https://alpha-bookshelf-app.vercel.app/book/diary-of-a-wimpy-kid",
  },
  {
    id: "dogtown",
    title: "Dogtown",
    shortTitle: "Dogtown",
    author: "Katherine Applegate and Gennifer Choldenko",
    year: "2023",
    description: "Chance is a real dog stuck at a shelter. Metal Head is a robot dog left behind by his kid. Together, they hatch a plan to get home.",
    cover: "#8b6b3f",
    accent: "#e8dcbc",
    ink: "#f4ead8",
    grade: null,
    lexile: null,
    shells: ["quest"] as Shell[],
    badges: ["kid favorite", "kid voted award", "read aloud favorite"],
    coverImage: null,
    url: "https://alpha-bookshelf-app.vercel.app/book/dogtown",
  },
  {
    id: "narwhal",
    title: "Narwhal: Unicorn of the Arctic",
    shortTitle: "Narwhal: Unicorn of the Arctic",
    author: "Candace Fleming",
    year: "2022",
    description: "Everything true and strange about narwhals—the real unicorns of the Arctic—told by a naturalist who loves them.",
    cover: "#3f6e8f",
    accent: "#e8ecf5",
    ink: "#f4ead8",
    grade: null,
    lexile: null,
    shells: ["quest"] as Shell[],
    badges: ["bestseller", "kid voted award", "read aloud favorite"],
    coverImage: null,
    url: "https://alpha-bookshelf-app.vercel.app/book/narwhal",
  },
  {
    id: "the-lion-the-witch-and-the-wardrobe",
    title: "The Lion, the Witch and the Wardrobe",
    shortTitle: "The Lion, the Witch and the Wardrobe",
    author: "C. S. Lewis",
    year: "1950",
    description: "Lucy steps through a coat closet into a snowy wood and finds a lamppost, a faun, and a talking beaver. Something great and shaggy is coming, and the winter is finally beginning to melt.",
    cover: "#c4711f",
    accent: "#2b2418",
    ink: "#f5ead7",
    grade: "Grades 4-8",
    lexile: 940,
    shells: ["quest"] as Shell[],
    badges: ["kid favorite", "read aloud favorite"],
    coverImage: "/covers/the-lion-the-witch-and-the-wardrobe.jpg",
    url: "https://alpha-bookshelf-app.vercel.app/book/the-lion-the-witch-and-the-wardrobe",
  },
  {
    id: "lost-library",
    title: "The Lost Library",
    shortTitle: "The Lost Library",
    author: "Rebecca Stead and Wendy Mass",
    year: "2023",
    description: "A ghostly librarian, a talking cat, and a Little Free Library full of missing books lead Evan to a town secret he never knew existed.",
    cover: "#5a7a8f",
    accent: "#e8c48a",
    ink: "#f4ead8",
    grade: null,
    lexile: null,
    shells: ["quest"] as Shell[],
    badges: ["expert loved", "kid voted award"],
    coverImage: null,
    url: "https://alpha-bookshelf-app.vercel.app/book/lost-library",
  },
  {
    id: "trouble-with-heroes",
    title: "The Trouble with Heroes",
    shortTitle: "The Trouble with Heroes",
    author: "Kate Messner",
    year: "2024",
    description: "Twelve-year-old Finn is sentenced to hike his late father's mountain trail, and each summit peels back one more layer of the boy he used to be.",
    cover: "#2f4a5c",
    accent: "#c48a4a",
    ink: "#f4ead8",
    grade: "Grades 6-8",
    lexile: 1050,
    shells: ["quest", "teen"] as Shell[],
    badges: ["expert loved", "kid favorite", "kid voted award"],
    coverImage: "/covers/trouble-with-heroes.jpg",
    url: "https://alpha-bookshelf-app.vercel.app/book/trouble-with-heroes",
  },
  {
    id: "the-wild-robot",
    title: "The Wild Robot",
    shortTitle: "The Wild Robot",
    author: "Peter Brown",
    year: "2016",
    description: "When robot Roz opens her eyes for the first time, she discovers that she is alone on a remote, wild island. She has no idea how she got there or what her purpose is--but she knows she needs to survive.",
    cover: "#5a7d78",
    accent: "#e8c48a",
    ink: "#f4ead8",
    grade: null,
    lexile: null,
    shells: ["quest"] as Shell[],
    badges: ["bestseller", "kid voted award", "read aloud favorite"],
    coverImage: "/covers/the-wild-robot.jpg",
    url: "https://alpha-bookshelf-app.vercel.app/book/the-wild-robot",
  },
  {
    id: "hatchet",
    title: "Hatchet",
    shortTitle: "Hatchet",
    author: "Gary Paulsen",
    year: "1987",
    description: "Brian Robison, a teenage boy struggling through his parents divorce, is flying up north to stay with his dad for the summer. However, his plane crashes and he is forced to survive the Canadian wilderness. Now living in a world completely opposite of his own, he is now able to discover himself in this forsaken and…",
    cover: "#2a4a2e",
    accent: "#c48a4a",
    ink: "#f4ead8",
    grade: "Grades 6-8",
    lexile: 1020,
    shells: ["teen"] as Shell[],
    badges: ["bestseller", "kid favorite", "read aloud favorite"],
    coverImage: "/covers/hatchet.jpg",
    url: "https://alpha-bookshelf-app.vercel.app/book/hatchet",
  },
  {
    id: "magnolia-wu-unfolds-it-all",
    title: "Magnolia Wu Unfolds It All",
    shortTitle: "Magnolia Wu Unfolds It All",
    author: "Chanel Miller",
    year: "2024",
    description: "Magnolia Wu spends her summer at her family's Manhattan laundromat solving the mystery of one unclaimed sock at a time.",
    cover: "#c78098",
    accent: "#3555e0",
    ink: "#f4ead8",
    grade: "Grades 4-8",
    lexile: 850,
    shells: ["teen"] as Shell[],
    badges: ["kid voted award", "read aloud favorite"],
    coverImage: "/covers/magnolia-wu-unfolds-it-all.jpg",
    url: "https://alpha-bookshelf-app.vercel.app/book/magnolia-wu-unfolds-it-all",
  },
  {
    id: "matilda",
    title: "Matilda",
    shortTitle: "Matilda",
    author: "Roald Dahl",
    year: "1988",
    description: "It's a funny thing about mothers and fathers.",
    cover: "#1e2f5c",
    accent: "#f5c94a",
    ink: "#f5c94a",
    grade: "Grades 4-8",
    lexile: 840,
    shells: ["teen"] as Shell[],
    badges: ["bestseller", "kid favorite", "read aloud favorite"],
    coverImage: "/covers/matilda.jpg",
    url: "https://alpha-bookshelf-app.vercel.app/book/matilda",
  },
  {
    id: "simon-sort-of-says",
    title: "Simon Sort of Says",
    shortTitle: "Simon Sort of Says",
    author: "Erin Bow",
    year: "2023",
    description: "Simon and his family move to a town with no internet so he can finally stop being the boy from the news. Then a squirrel, an astronomer, and a girl with a plan find him anyway.",
    cover: "#7a3a3a",
    accent: "#e8c48a",
    ink: "#f4ead8",
    grade: "Grades 6-8",
    lexile: 1050,
    shells: ["teen"] as Shell[],
    badges: ["expert loved", "kid voted award"],
    coverImage: "/covers/simon-sort-of-says.jpg",
    url: "https://alpha-bookshelf-app.vercel.app/book/simon-sort-of-says",
  },
  {
    id: "cartoonists-club",
    title: "The Cartoonists Club",
    shortTitle: "The Cartoonists Club",
    author: "Raina Telgemeier and Scott McCloud",
    year: "2025",
    description: "Four kids start a cartoonists club at school and learn how to write, draw, and tell stories together—an all-ages love letter to making comics.",
    cover: "#eae4d2",
    accent: "#3555e0",
    ink: "#1e1a12",
    grade: "Grades 4-8",
    lexile: 900,
    shells: ["teen"] as Shell[],
    badges: ["graphic novel", "kid voted award"],
    coverImage: "/covers/cartoonists-club.jpg",
    url: "https://alpha-bookshelf-app.vercel.app/book/cartoonists-club",
  },
  {
    id: "the-hunger-games",
    title: "The Hunger Games",
    shortTitle: "The Hunger Games",
    author: "Suzanne Collins",
    year: "2008",
    description: "The Hunger Games is a 2008 dystopian novel by the American writer Suzanne Collins. It is written in the perspective of 16-year-old Katniss Everdeen, who lives in the future, post-apocalyptic nation of Panem in North America. The Capitol, a highly advanced metropolis, exercises political control over the rest of the…",
    cover: "#1e1a12",
    accent: "#e8a53a",
    ink: "#f4ead8",
    grade: "Grades 4-8",
    lexile: 810,
    shells: ["teen"] as Shell[],
    badges: ["bestseller", "kid voted award", "read aloud favorite"],
    coverImage: "/covers/the-hunger-games.jpg",
    url: "https://alpha-bookshelf-app.vercel.app/book/the-hunger-games",
  },
  {
    id: "misfits",
    title: "The Misfits: A Royal Conundrum",
    shortTitle: "The Misfits: A Royal Conundrum",
    author: "Lisa Yee",
    year: "2024",
    description: "Three misfit kids get recruited to a top-secret spy school for kids who don't quite fit in—and together they become exactly the team the mission needs.",
    cover: "#7a3a6a",
    accent: "#e8c48a",
    ink: "#f4ead8",
    grade: "Grades 4-8",
    lexile: 820,
    shells: ["teen"] as Shell[],
    badges: ["kid voted award"],
    coverImage: "/covers/misfits.jpg",
    url: "https://alpha-bookshelf-app.vercel.app/book/misfits",
  },
];

// Back-compat: existing template.ts imports `stripePressBooks`.
// Re-export the kids list under that name so nothing else breaks.
export const stripePressBooks = alphaBookshelfKids;
