export type LibraryBook = {
  id: string;
  title: string;
  shortTitle: string;
  author: string;
  year: string;
  description: string;
  cover: string;
  accent: string;
  ink: string;
  url: string;
};

export const stripePressBooks: LibraryBook[] = [
  {
    id: "maintenance",
    title: "Maintenance: Of Everything, Part One",
    shortTitle: "Maintenance",
    author: "Stewart Brand",
    year: "2025",
    description: "A civilizational history of upkeep—and an argument for care as a radical, future-making practice.",
    cover: "#668f83",
    accent: "#c98359",
    ink: "#f4ead8",
    url: "https://press.stripe.com/maintenance-part-one",
  },
  {
    id: "scaling",
    title: "The Scaling Era",
    shortTitle: "The Scaling Era",
    author: "Dwarkesh Patel with Gavin Leech",
    year: "2025",
    description: "An oral history of modern AI told through conversations with the researchers and founders shaping large models.",
    cover: "#172e56",
    accent: "#e4683d",
    ink: "#f4eee2",
    url: "https://press.stripe.com/scaling",
  },
  {
    id: "art-of-science",
    title: "The Art of Doing Science and Engineering",
    shortTitle: "The Art of Doing Science",
    author: "Richard W. Hamming",
    year: "2020",
    description: "Richard Hamming on great work, creative problem-solving, and tackling consequential questions.",
    cover: "#d96e3d",
    accent: "#282522",
    ink: "#f5ead7",
    url: "https://press.stripe.com/the-art-of-doing-science-and-engineering",
  },
  {
    id: "poor-charlie",
    title: "Poor Charlie’s Almanack",
    shortTitle: "Poor Charlie’s Almanack",
    author: "Edited by Peter D. Kaufman",
    year: "2023",
    description: "Charles T. Munger’s talks and lessons become a practical latticework for clearer thinking and continual learning.",
    cover: "#762331",
    accent: "#d5a756",
    ink: "#f4ead7",
    url: "https://press.stripe.com/poor-charlies-almanack",
  },
  {
    id: "high-growth",
    title: "High Growth Handbook",
    shortTitle: "High Growth Handbook",
    author: "Elad Gil",
    year: "2018",
    description: "A field guide to the inflection points that arrive after product-market fit.",
    cover: "#1c304b",
    accent: "#d45949",
    ink: "#f1e7d4",
    url: "https://press.stripe.com/high-growth-handbook",
  },
  {
    id: "origins-efficiency",
    title: "The Origins of Efficiency",
    shortTitle: "Origins of Efficiency",
    author: "Brian Potter",
    year: "2025",
    description: "A whole-systems investigation into how production becomes faster, cheaper, and more reliable.",
    cover: "#e8ddc6",
    accent: "#df5c4c",
    ink: "#263f70",
    url: "https://press.stripe.com/origins-of-efficiency",
  },
  {
    id: "scaling-people",
    title: "Scaling People",
    shortTitle: "Scaling People",
    author: "Claire Hughes Johnson",
    year: "2023",
    description: "An empathetic operating manual for leaders building durable organizations.",
    cover: "#e87d68",
    accent: "#17304b",
    ink: "#f8ecdc",
    url: "https://press.stripe.com/scaling-people",
  },
  {
    id: "revolt-public",
    title: "The Revolt of the Public",
    shortTitle: "The Revolt of the Public",
    author: "Martin Gurri",
    year: "2018",
    description: "How networked publics shattered information monopolies and transformed political authority.",
    cover: "#e7e1d3",
    accent: "#d44c40",
    ink: "#212121",
    url: "https://press.stripe.com/the-revolt-of-the-public",
  },
  {
    id: "big-score",
    title: "The Big Score",
    shortTitle: "The Big Score",
    author: "Michael S. Malone",
    year: "2021",
    description: "A panoramic history of Silicon Valley’s hardware beginnings and semiconductor breakthroughs.",
    cover: "#25282a",
    accent: "#e15c48",
    ink: "#eee4ce",
    url: "https://press.stripe.com/the-big-score",
  },
  {
    id: "elegant-puzzle",
    title: "An Elegant Puzzle",
    shortTitle: "An Elegant Puzzle",
    author: "Will Larson",
    year: "2019",
    description: "A systems-minded handbook for engineering leaders confronting organizational design and team growth.",
    cover: "#deded8",
    accent: "#3975b3",
    ink: "#242629",
    url: "https://press.stripe.com/an-elegant-puzzle",
  },
  {
    id: "boom",
    title: "Boom: Bubbles and the End of Stagnation",
    shortTitle: "Boom",
    author: "Byrne Hobart and Tobias Huber",
    year: "2024",
    description: "How bubbles assemble capital, talent, urgency, and risk to unlock transformative innovation.",
    cover: "#262421",
    accent: "#f16f5b",
    ink: "#d9edf0",
    url: "https://press.stripe.com/boom",
  },
  {
    id: "prince-persia",
    title: "The Making of Prince of Persia",
    shortTitle: "Making Prince of Persia",
    author: "Jordan Mechner",
    year: "2020",
    description: "The candid development journals behind a landmark game, tracing invention in real time.",
    cover: "#dec796",
    accent: "#9b3741",
    ink: "#272523",
    url: "https://press.stripe.com/the-making-of-prince-of-persia",
  },
  {
    id: "flying-car",
    title: "Where Is My Flying Car?",
    shortTitle: "Where Is My Flying Car?",
    author: "J. Storrs Hall",
    year: "2021",
    description: "An investigation into technological stagnation and the ambition required to build physical abundance.",
    cover: "#83b8ce",
    accent: "#e6673c",
    ink: "#f7f3e8",
    url: "https://press.stripe.com/where-is-my-flying-car",
  },
  {
    id: "working-public",
    title: "Working in Public",
    shortTitle: "Working in Public",
    author: "Nadia Eghbal",
    year: "2020",
    description: "An intimate look at open-source communities and the structures beneath software’s public surface.",
    cover: "#2457a8",
    accent: "#d6df45",
    ink: "#f3efe3",
    url: "https://press.stripe.com/working-in-public",
  },
  {
    id: "stubborn-attachments",
    title: "Stubborn Attachments",
    shortTitle: "Stubborn Attachments",
    author: "Tyler Cowen",
    year: "2018",
    description: "A case for sustainable growth, human rights, and moral concern for distant generations.",
    cover: "#365943",
    accent: "#c7a45e",
    ink: "#eee7d6",
    url: "https://press.stripe.com/stubborn-attachments",
  },
  {
    id: "scientific-freedom",
    title: "Scientific Freedom",
    shortTitle: "Scientific Freedom",
    author: "Donald W. Braben",
    year: "2008",
    description: "A case for protecting unconventional researchers so improbable discoveries can survive.",
    cover: "#4c3970",
    accent: "#9ad3bf",
    ink: "#f3ecdb",
    url: "https://press.stripe.com/scientific-freedom",
  },
  {
    id: "pieces-action",
    title: "Pieces of the Action",
    shortTitle: "Pieces of the Action",
    author: "Vannevar Bush",
    year: "2022",
    description: "A first-person account of coordinating scientists, institutions, and government at enormous scale.",
    cover: "#626a49",
    accent: "#a4433e",
    ink: "#eee5cf",
    url: "https://press.stripe.com/pieces-of-the-action",
  },
  {
    id: "get-together",
    title: "Get Together",
    shortTitle: "Get Together",
    author: "Bailey Richardson, Kevin Huynh, and Kai Elmer Sotto",
    year: "2019",
    description: "A practical guide to finding a community’s first believers and turning an audience into belonging.",
    cover: "#e6bc39",
    accent: "#8f2f45",
    ink: "#244a6d",
    url: "https://press.stripe.com/get-together",
  },
  {
    id: "dream-machine",
    title: "The Dream Machine",
    shortTitle: "The Dream Machine",
    author: "M. Mitchell Waldrop",
    year: "2018",
    description: "The history of the visionaries who transformed the computer into a personal medium.",
    cover: "#9a8ab8",
    accent: "#f0b154",
    ink: "#f5eedf",
    url: "https://press.stripe.com/the-dream-machine",
  },
];
